### ISSUE TITLE
Frontend: Focus in textfield by default

### ISSUE THREAD

**Issue by mcandre** [toptal/gitignore.io#154]
For speed, it would be nice if the gitignore.io website automatically focused inside the search box, so that I can more quickly generate patterns.

**Comment by joeblau** [comment]
This is an issue with Select2 4.0: https://github.com/select2/select2/issues/3696  Once this issue is resolved, I'll update the gitignore.io.

**Comment by stefnotch** [comment]
Can we reopen this issue, as the [external dependency's bug has been fixed](https://github.com/select2/select2/issues/3696)?

The issue, as described in the original post is still present. (Firefox 64)

**Comment by joeblau** [comment]
Yep!

**Comment by christianlerke** [comment]
The issue has been resolved. When opening the page the field is automatically focussed
