### ISSUE TITLE
Missing names in eclipse gitignore file

### ISSUE THREAD

**Issue by akoita** [toptal/gitignore.io#31]
Hello,

Thank you for the practical tool that is gitignore.io. 

I just remarked that in the gitignore file generated for eclipse, these files/directory names are missing: .classpath, .settings and .projetc. These files miss intentionaly or this
is just a forgetting?

Regards,
Aboubakar

**Comment by segfly** [comment]
Good news, everyone! Eclipse gitignore .classpath and .project have been merged upstream in github/gitignore@8bc0e535bbc450e329cc8714da5c74855e3e98ea

**Comment by joeblau** [comment]
I've also added it to the .patch file https://www.gitignore.io/api/eclipse.  I'll take them out when I pull the GitHub's master list:
