### ISSUE TITLE
No create

### ISSUE THREAD

**Issue by MrLichangming** [toptal/gitignore.io#378]
In the web interface, I entered python in the textbox, unable to create, what caused this?

**Comment by joeblau** [comment]
Are you trying to run the site locally?

**Comment by onion2k** [comment]
I get the same problem (Chrome 63.0.3239.84 on OSX).

More info - If I type python in to the box and *don't* click the suggestion but click the 'Create' button instead the UI assumes there was nothing entered. It's only working if I click the suggestion first.

**Comment by joeblau** [comment]
Ah I see.  I think that is a function of the Select2 library that I'm using.  It's not smart enough to figure out what you mean if you don't select something from the drop down.   This is probably going to remain an open issue until I have a chance to see if Select2 updated this behavior for tagged fields.

For now, you'll have to select an item from the drop down before pressing create.
