### ISSUE TITLE
dyld: Library not loaded: @rpath/libssl.1.0.0.dylib

### ISSUE THREAD

**Issue by Annihilater** [toptal/gitignore.io#443]
I got questions when Iuser gi, please help!

It was on mac iterm zsh.

![](https://ws4.sinaimg.cn/large/006tNc79gy1fzl2fz5mduj31ns0aamyo.jpg)

how to fix it. I have already install by command
`$ echo "function gi() { curl -L -s https://www.gitignore.io/api/\$@ ;}" >> ~/.zshrc && source ~/.zshrc
`

I have tried 
`brew update & brew upgrade`
but not work.

**Comment by joeblau** [comment]
try `brew install openssl`

**Comment by christianlerke** [comment]
If this is still an issue please reopen it
