### ISSUE TITLE
As support for dockerignore

### ISSUE THREAD

**Issue by s7726** [toptal/gitignore.io#448]
The format appears to be the same.

Could support various other ignore files also!

git.ignore.io
docker.ignore.io

**Comment by joeblau** [comment]
It looks like someone already owns the ignore.io TLD unfortunately.

**Comment by s7726** [comment]
Pretty sure they are just squatting on it.
Can probably grab dockerignore.io

**Comment by joeblau** [comment]
I just sent the owner of ignore.io a message.  Let's see what they say.

**Comment by tpiekarski** [comment]
Any news about it?

**Comment by joeblau** [comment]
I'm going to close this — this site has already been sold and there is not enough of a financial incentive to build dockerignore sustainability.
