### ISSUE TITLE
VS 2019 Live share ignore file

### ISSUE THREAD

**Issue by puremonk** [toptal/gitignore.io#455]
## Issue
.ide file is not ignored when sharing a project in Visual studio 2019
The location of the file: .vs\{Project}\v16\Server\sqlite3

### Development Environment:

- [x] Machine (Local, Container, Virtual): Local
- [x] Operating System (Name/Version): Windows 10 1803
- [x] Web Browser (Name/Version): Opera
- [ ] Vapor Version: -
- [ ] Swift Version: -

### Expected Behavior:
Ignoring the .ide file named "storage.ide" located in ".vs\{Project}\v16\Server\sqlite3"

### Actual Behavior:
Not ignored

### Reproduction Steps:
Use visual studio 2019 (v 16.0.2) live share tool in a (C#) project.

**Comment by joeblau** [comment]
Thanks for the suggestions, all of the templates for gitignore.io are hosted here: https://github.com/toptal/gitignore. If you submit a PR in that repo, you'll get credit as a contributor and I can merge it in the next round.
