### ISSUE TITLE
Docker build error, need swift v4.0.0

### ISSUE THREAD

**Issue by Windforce17** [toptal/gitignore.io#456]
`Error: backgroundExecute(code: 1, error: "swift-package: error: Package requires minimum Swift tools version 4.0.0. Current Swift tools version is 3.1.0\n", output: "")
ERROR: Service 'app' failed to build: The command '/bin/sh -c vapor build' returned a non-zero code: 1`

maybe Dockerfile need to update?

**Comment by christianlerke** [comment]
`Dockerfile` has been updated and it works now
