### ISSUE TITLE
Contributing fish completion?

### ISSUE THREAD

**Issue by zubin** [toptal/gitignore.io#458]
Inspired by the [zsh completion](https://docs.gitignore.io/use/advanced-command-line#oh-my-zsh), I wrote fish completion for `git ignore`. 

Is there a docs repo where I can contribute this?

**Comment by joeblau** [comment]
Paste the script here and I'll add it. I used to have a repo that mirrored the docs, but gitbook.com got sensitive about changes that weren't exactly right.

**Comment by zubin** [comment]
```fish
complete -f -c git -n '__fish_git_using_command ignore' -a '(__fish_print_gitignore_list)'

function __fish_print_gitignore_list
  if ! set -q __FISH_PRINT_GITIGNORE_LIST
    set -g __FISH_PRINT_GITIGNORE_LIST (curl -sL https://www.gitignore.io/api/list)
  end
  echo $__FISH_PRINT_GITIGNORE_LIST | string split ","
end
```

**Comment by joeblau** [comment]
Thanks @zubin I added that here: https://app.gitbook.com/@dvcs/s/gitignore-io-docs/use/advanced-command-line#zubin
