### ISSUE TITLE
Suggestion: Offer in Homebrew

### ISSUE THREAD

**Issue by nottoseethesun** [toptal/gitignore.io#459]
It would be great if this were available as `brew install gitignore` or similar.   Then there could be a config option to set it to the invocation means of the user's preference.

**Comment by dnedrow** [comment]
@nottoseethesun , this would be pretty simple to provide, given that the only thing that would need to be provided in the brew package is the function — that warps the curl command — for the various shells.

You could take a look at the brew docs to see how to submit a new package.

Alternatively, if you use "Oh My ZSH!", you can enable to gitignore plugin (gi).

**Comment by joeblau** [comment]
@dnedrow is right — this would mostly be about getting the shell command into the homebrew repo.

**Comment by ZevEisenberg** [comment]
It would be nice if it worked offline as well, so maybe it could bundle the various ignore files instead of using cURL?

**Comment by nottoseethesun** [comment]
Yes it seems like the gitignore files would be small data, so they could just be bundled in with the initial download.
