### ISSUE TITLE
.idea folder is not excluded from gitignore in intellij

### ISSUE THREAD

**Issue by amitsandesara** [toptal/gitignore.io#460]
Is there a reason why the '.idea' folder is not excluded from intellij's gitignore?
Because it adds the idea folder to commit. After looking into it, I found the vcs.xml file in the .idea folder is not getting excluded.

_This is what *git status* shows in Intellij._
![image](https://user-images.githubusercontent.com/14857220/65442200-5d149e80-ddf1-11e9-85e0-e2d89679a405.png)

**Comment by joeblau** [comment]
The template does ignore parts of the `.idea/` directory, just not the whole directory.

https://github.com/toptal/gitignore/blob/master/templates/JetBrains.gitignore#L4-L25

There is a comment in the template to ignore more if you're using gradle or maven.

https://github.com/toptal/gitignore/blob/master/templates/JetBrains.gitignore#L27-L35

**Comment by amitsandesara** [comment]
Yeah, but can  vcs.xml be added to the exclusion set?

**Comment by joeblau** [comment]
Sure, add it to the template list: https://github.com/toptal/gitignore
