### ISSUE TITLE
Suggestion: Generic Build/dist template

### ISSUE THREAD

**Issue by skycaptain** [toptal/gitignore.io#470]
`build` and `dist` folders are very common across many languages and toolchains, e.g. Makefiles, etc. Some templates already so exclude those folders, some do not, as they are not very common for those languages, e.g. `Matlab`. But still they are used and sometimes I'm missing them in a template. How about a generic language-agnostic Build/Dist template?

`build+dist.gitignore`:
```gitignore
build/
dist/
```

**Comment by joeblau** [comment]
This is great idea, can you, please submit this template to https://github.com/toptal/gitignore
