### ISSUE TITLE
IntelliJ: should .idea/misc.xml really be excluded?

### ISSUE THREAD

**Issue by davidkron** [toptal/gitignore.io#472]
Currently the file `.idea/misc.xml` is excluded when using `Intellij+iml` on gitignore.io.

I'm not sure if this is correct.
In my project this file has the following content:
```
  <component name="JavaScriptSettings">
    <option name="languageLevel" value="ES6" />
  </component>
```

This clearly specifies a project specific configuration which should be shared in a team.

**Comment by joeblau** [comment]
Please submit template PR's to https://github.com/toptal/gitignore
