### ISSUE TITLE
STS - Spring Tool Suite not covered

### ISSUE THREAD

**Issue by helenou** [toptal/gitignore.io#475]
STS is not part of the IDE covered apparently.

It seems one can already exclude the following :
** .sts4-cache/
** .springbeans
** spring-test/test-output/
** /spring-*/build
** /spring-core/kotlin-coroutines/build
** spring-*/src/main/java/META-INF/MANIFEST.MF

Thanks for adding support for Spring and STS in the future, and more if needed ;)

**Comment by joeblau** [comment]
Thanks for the suggestions, all of the templates for gitignore.io are hosted here: https://github.com/toptal/gitignore.  If you submit a PR in that repo, you'll get credit as a contributor and I can merge it in the next round.
