### ISSUE TITLE
Support .gitignorerc pattern (doc suggestion/feature request)

### ISSUE THREAD

**Issue by matthewadams** [toptal/gitignore.io#486]
### Development Environment:

- [x] Machine (Local, Container, Virtual): Local
- [x] Operating System (Name/Version): macOS
- [x] Web Browser (Name/Version): Chrome/79.0.3945.130 (Official Build) (64-bit)
- [ ] Vapor Version:
- [ ] Swift Version:

### Expected Behavior:
N/A

### Actual Behavior:
N/A

### Reproduction Steps:
N/A

This issue is simply a documentation suggestion of a pattern we use in our projects.

We commit a file called `.gitignorerc` with content similar to the following:
```
macos,linux,windows,jetbrains+all,eclipse,code,node
# the above line is passed to gitignore.io; add anything custom below, then execute .gitignore.sh
```
The first line contains the arguments that will be given by the script below to gitignore.io.  Anything after the first line is simply appended to the `.gitignore` file, so that we can have additional ignores without having to worry about maintaining the `.gitignore` file manually.

We commit the script below as `.gitignore.sh`, alongside `.gitignorerc`:
```
RC=.gitignorerc

curl -sL https://www.gitignore.io/api/$(head -1 $RC) > .gitignore
tail -n +2 $RC >> .gitignore
```

Actually, it just occurred to me that if you wanted to formalize this pattern into a new feature where gitignore would look for a `.gitignorerc` file and/or accept literal ignore patterns as a command line argument, it'd be pretty neat.  :)

Anyway, thanks for gitignore.io.

**Comment by Zaiko235** [comment]
Agregar al patrón

**Comment by matthewadams** [comment]
Please don't close
