### ISSUE TITLE
venv is include in source(toptal/gitignore/Python.gitignore) but not on gitignore.io

### ISSUE THREAD

**Issue by AnyOfYou** [toptal/gitignore.io#487]
Hi,
I found out that 'venv' is include in [source](https://github.com/toptal/gitignore/blob/master/templates/Python.gitignore), but still not include in the [website](https://www.gitignore.io/api/python)

**Comment by DjMoren** [comment]
I come here to say the same, in my case for _.venv_.  If I go to the templates project, the python gitignore generated is different from the one that I see there...

**Comment by acbetter** [comment]
Same issue here. My temporary fix method is add `venv` to templates, for example [https://www.gitignore.io/?templates=code,venv,linux,macos,python,windows](https://www.gitignore.io/?templates=code,venv,linux,macos,python,windows)

**Comment by christianlerke** [comment]
It is now also included when using the website.
See https://www.toptal.com/developers/gitignore/api/python
