### ISSUE TITLE
Suggestion: Add vs as an alias of VisualStudio

### ISSUE THREAD

**Issue by doggy8088** [toptal/gitignore.io#492]
When I'm using command line to download `VisualStudio` template. I have to type this:

```sh
git ignore visualstudio
```

It because `vs` is very common short name of Visual Studio. Is it possible to add an `vs` alias for `VisualStudio`? So that I can type command like this:

```sh
git ignore vs
```

**Comment by lucis** [comment]
Also searching on the homepage for "VS" (usually how people refer to VS Code) doesn't return anything

**Comment by doggy8088** [comment]
@lucis What `homepage` do  you mean?
