### ISSUE TITLE
please update for joomla 4 and update joomla 3

### ISSUE THREAD

**Issue by N6REJ** [toptal/gitignore.io#497]
# Issue Template
### Development Environment:

- [ ] Machine (Local, Container, Virtual):
http://neard.io

- [ ] Operating System (Name/Version):
win 10 x64 pro

- [ ] Web Browser (Name/Version):
ff & chrome

- [ ] Vapor Version:
- [ ] Swift Version:

### Expected Behavior:
works for joomla 4
### Actual Behavior:
works only for joomla 3
### Reproduction Steps:
search for joomla 4 nothing found.
joomla returns files based on older joomla 3.

**Comment by joeblau** [comment]
Please submit templates to the template repository: https://github.com/toptal/gitignore

**Comment by N6REJ** [comment]
@joeblau joomla isn't a template it's a cms

**Comment by joeblau** [comment]
This site is not designed to run on a CMS. It's a stand alone application.
