### ISSUE TITLE
Why the domain name change?

### ISSUE THREAD

**Issue by abhisekp** [toptal/gitignore.io#502]
Toptal has a logo in the page itself.

What's the reasoning behind changing the page url? `gitignore.io` is pretty url.   
This is not `https://www.toptal.com/developers/gitignore`

https://github.com/toptal/gitignore.io/issues/496

**Comment by christianlerke** [comment]
This has already been answered in the issue you referenced: "Due to business requirements, we can't serve the page from gitignore.io directly..."

https://github.com/toptal/gitignore.io/issues/496#issuecomment-644411787
