### ISSUE TITLE
VB.NET support

### ISSUE THREAD

**Issue by unwaged** [toptal/gitignore.io#503]
### Expected Behavior:
VB.NET should be in the list of programming languages like c#
### Actual Behavior:
VB.NET is not in the programming list
### Reproduction Steps:
just type vb.net or visual basic with no result

**Comment by christianlerke** [comment]
Hello @unwaged,
Templates are stored here: https://github.com/toptal/gitignore/tree/master/templates

If you cannot find what you're looking for feel free to open a PR to add a new template.
