### ISSUE TITLE
macOS gitignore file generated by gitignore.io is broken

### ISSUE THREAD

**Issue by tmsick** [toptal/gitignore.io#504]
When I curl https://github.com/toptal/gitignore/blob/master/templates/macOS.gitignore directly from GitHub, the file has two `\r` following `Icon`, and it looks OK. But if I curl https://www.toptal.com/developers/gitignore/api/macos from gitignore.io app page, the resulting file has only one `\r` after `Icon`.

I think this is not a good situation. Does anyone have a clue to solve this?

**Comment by christianlerke** [comment]
We're investigating it

**Comment by christianlerke** [comment]
The API returns the expected result:
```
Net::HTTP.get_response(URI.parse("https://www.toptal.com/developers/gitignore/api/macos")).body
 => "\n# Created by https://www.toptal.com/developers/gitignore/api/macos\n# Edit at https://www.toptal.com/developers/gitignore?templates=macos\n\n### macOS ###\n# General\n.DS_Store\n.AppleDouble\n.LSOverride\n\n# Icon must end with two \\r\nIcon\r\n\n# Thumbnails\n._*\n\n# Files that might appear in the root of a volume\n.DocumentRevisions-V100\n.fseventsd\n.Spotlight-V100\n.TemporaryItems\n.Trashes\n.VolumeIcon.icns\n.com.apple.timemachine.donotpresent\n\n# Directories potentially created on remote AFP share\n.AppleDB\n.AppleDesktop\nNetwork Trash Folder\nTemporary Items\n.apdisk\n\n# End of https://www.toptal.com/developers/gitignore/api/macos\n"
```
See `# Icon must end with two \\r\nIcon\r\n\n`

**Comment by christianlerke** [comment]
Hi @tmsick,
the issue has been resolved

**Comment by gimbo** [comment]
Might be worth keeping an eye on [this upstream PR](https://github.com/github/gitignore/pull/3523) as if this gets merged then the need for this fix potentially goes away (depending on exactly what gets merged).
