### ISSUE TITLE
remove leading space in commented code

### ISSUE THREAD

**Issue by elect86** [toptal/gitignore.io#505]
This

https://www.toptal.com/developers/gitignore/api/java,gradle,intellij,kotlin

generates the following:

```
# Gradle and Maven with auto-import
# When using Gradle or Maven with auto-import, you should exclude module files,
# since they will be recreated, and may cause churn.  Uncomment if using
# auto-import.
# .idea/artifacts
# .idea/compiler.xml
# .idea/jarRepositories.xml
# .idea/modules.xml
# .idea/*.iml
# .idea/modules
# *.iml
# *.ipr
```

but all the commented lines have a leading space which, if uncommented with ctrl+`/`, will remain and make the ignored file be still visible in the Idea commit dialog

you need to remove the leading space

```
# Gradle and Maven with auto-import
# When using Gradle or Maven with auto-import, you should exclude module files,
# since they will be recreated, and may cause churn.  Uncomment if using
# auto-import.
#.idea/artifacts
#.idea/compiler.xml
#.idea/jarRepositories.xml
#.idea/modules.xml
#.idea/*.iml
#.idea/modules
#*.iml
#*.ipr
```

### Development Environment:

- Machine: Local
- Operating System: Win10 x64
- Web Browser: FF 80.0.1

**Comment by doggy8088** [comment]
@elect86 I don't have this issue in my VSCode. What editor do you use?

**Comment by elect86** [comment]
Idea

**Comment by doggy8088** [comment]
I think it's Tool-dependent issue. You might be able to suggest Idea to handle this.

**Comment by elect86** [comment]
True, but given that:

- `gitignore.io` generates it
- all the other entries do not have a leading space

I'd say it make sense to fix this at the generation place

**Comment by christianlerke** [comment]
As @doggy8088 correctly said this is a tool dependent issue.
Best practice is to include a space for readability.
A quick search of all templates https://github.com/toptal/gitignore/tree/master/templates shows that the majority of code comments have spaces.

**Comment by elect86** [comment]
@christianlerke 

I quickly checked the very first 5 templates of your link, I found no entry with leading spaces

Anyway, I don't want to sound polemic and this is not a big issue, I just wanted to be constructive and solve this for other people like me, I give up
