### ISSUE TITLE
VisualStudioCode insists on preserving files I do not want

### ISSUE THREAD

**Issue by mcandre** [toptal/gitignore.io#506]
```
!.vscode/settings.json
!.vscode/tasks.json
!.vscode/launch.json
!.vscode/extensions.json
```

**Comment by christianlerke** [comment]
Hi @mcandre,
Templates are defined here: https://github.com/toptal/gitignore/tree/master/templates
Looks like there already is a PR relating to this: https://github.com/toptal/gitignore/pull/325
Please check it out and and your opinion as a comment
