### ISSUE TITLE
Add better documentation for CLI tool

### ISSUE THREAD

**Issue by codeman101** [toptal/gitignore.io#508]
Can you please add better documentation to the CLI tool. Aside from installing it via curl and adding it to the zsh file. I don't know how to actually use the tool.

**Comment by joeblau** [comment]
Does this help? https://docs.gitignore.io/use/command-line

**Comment by codeman101** [comment]
@joeblau :facepalm: my apologies. I wasn't looking at it correctly before. :facepalm: x100.
