### ISSUE TITLE
gi :type: does not generate .gitignore file

### ISSUE THREAD

**Issue by wzieba** [toptal/gitignore.io#512]
# Issue Template

## Frequently Asked Questions

**Q:** How do I submit a new <code>.gitignore</code> templates?  
**A:** Please submit all new templates to [@toptal/gitignore](https://github.com/toptal/gitignore).

**Q:** How do I suggest modifications to existing `.gitignore` templates?  
**A:** Modifictions should come in the form of pull requests at [@toptal/gitignore](https://github.com/toptal/gitignore).

**Q:** Why don't Gitignore.io's templates don't look exactly like the templates on [@github/gitignore](https://github.com/github/gitignore)?  
**A:** Gitignore.io tried to maintain parity with [@github/gitignore](https://github.com/github/gitignore), but GitHub's template list doesn't include many languages, operating systems, and IDE's that developers use.  Gitignore.io's template list has over 100 more templates than GitHub's.

**Q:** Why is my local site empty?  
**A:** When the repository is cloned, the `--recursive` flag is necessary.  gitignore.io uses [@toptal/gitignore](https://github.com/toptal/gitignore) as its data source.  If  the repo isn't cloned recursively, templates will be missing.

## Issue
Executing `gi android` (or any other type) does not create `.gitignore` file.

### Development Environment:

- [x] Machine (Local, Container, Virtual): Local
- [x] Operating System (Name/Version): MacOS, 10.15.7

### Expected Behavior:
Contentful `.gitignore` file should be created

### Actual Behavior:
Content of desired `.gitignore` is printed to the console output, but no file is created

### Reproduction Steps:
1. Setup function as [stated in docs ](https://docs.gitignore.io/install/command-line#masos-zsh)
```
echo "function gi() { curl -sLw "\n" https://www.toptal.com/developers/gitignore/api/\$@ ;}" >> \
~/.zshrc && source ~/.zshrc
```
2. Try to create `.gitignore` file by executing:
```
gi android
```

**Comment by gnechita-toptal** [comment]
Hey @wzieba I think there is a slight confusion here, the command doesn't create a `.gitignore` file, but returns as a response what you should add to a `.gitignore` file.

If you want to take that response and push it to a file try `touch .gitignore && gi android >> .gitignore` if the file doesn't exist, and if you just want to append the information try `gi android >> .gitignore`.

Here's more info about the command line usage: https://docs.gitignore.io/use/command-line
