### ISSUE TITLE
Update documentation for Windows CLI installation

### ISSUE THREAD

**Issue by MaskyS** [toptal/gitignore.io#516]
Adding the following line to https://docs.gitignore.io/install/command-line#windows would massively clarify the installation. 

```
Paste this script inside your Powershell profile (run `$profile` inside Powershell to get the profile's location path).
```

I can't find a way to open a PR of some sort to the Gitbook docs, so posting here.

**Comment by gnechita-toptal** [comment]
Done ✅  https://docs.gitignore.io/install/command-line#windows
