### ISSUE TITLE
Revert VisualStudioCode workspace changes

### ISSUE THREAD

**Issue by jerone** [toptal/gitignore.io#521]
I want cast my vote to revert recent VisualStudioCode change from here: toptal/gitignore#325. 

Anything inside the projects `.vscode` folder is not user specific, but project/workspace specific. It contains configurations that are shared across developers on current project. For example, to run our project we have some extensions that developer need to install, listed in `extensions.json`.

This is [documented](https://code.visualstudio.com/docs/getstarted/settings) by VSCode:

> Workspace settings override user settings. Workspace settings are specific to a project and can be shared across developers on a project.
> 
> **Note**: A VS Code "workspace" is usually just your project root folder. Workspace settings as well as [debugging](https://code.visualstudio.com/docs/editor/debugging) and [task](https://code.visualstudio.com/docs/editor/tasks) configurations are stored at the root in a `.vscode` folder. You can also have more than one root folder in a VS Code workspace through a feature called [Multi-root workspaces](https://code.visualstudio.com/docs/editor/multi-root-workspaces).

Besides the incorrect removal of workspace files, there is now also a misalignment between the following synonymous Visual Studio Code template files:

*   https://github.com/toptal/gitignore/blob/master/templates/vscode.gitignore (this one is correct)
*   https://github.com/toptal/gitignore/blob/master/templates/VisualStudioCode.gitignore

**Comment by christianlerke** [comment]
@jerone please create a PR with the changes in the https://github.com/toptal/gitignore repo.
We will review it there.
Thank you
