### ISSUE TITLE
Conflicting .gitignore rules cause important files to be ignored

### ISSUE THREAD

**Issue by ntratcliff** [toptal/gitignore.io#522]
## Issue

.gitignore includes conflicting rules when using multiple languages, IDEs, and OSes. 

### Development Environment:

- [ ] Machine (Local, Container, Virtual):
- [ ] Operating System (Name/Version):
- [x] Web Browser (Name/Version): Chrome Version 87.0.4280.141 (Official Build) (x86_64)
- [ ] Vapor Version:
- [ ] Swift Version:

### Expected Behavior:

.gitignore file properly ignores and includes specific files for the selected languages, IDEs, and OSes. In this case: Unity, Rider, macOS, Windows, and Fastlane.

### Actual Behavior:

Conflicting rules cause important files like Unity's `.meta` files to be excluded (in this case, by Visual Studio's `*.meta` rule).

### Reproduction Steps:

1. Go to gitignore.io and add the following: Unity, Rider, macOS, Windows, and Fastlane
2. Click "create"
3. Download .gitignore into a Unity project
4. Observe that `.meta` files are ignored

**Comment by christianlerke** [comment]
It seems to work fine with the list you provided. But when adding Visual Studio it does add the `*.meta` rule that is causing your issue.
Either do not include Visual Studio, or remove the offending line manually afterwards.
Gitignore is just a starting point and is not guaranteed to work out of the box when combining many different tools and operating systems.
