### ISSUE TITLE
Please do not host the sources on toptal.com

### ISSUE THREAD

**Issue by moltar** [toptal/gitignore.io#526]
I discovered it by my firewall triggering an alert that the actual ingore templates are on toptal.com.

I think in this day and age of privacy and tracking, it would be better if these templates were hosted elsewhere.

I think GitHub is a good place to put them.

if I block toptal.com in the firewall, then the script no longer works:

```
❯ git ignore-io nodejs
curl: (7) Failed to connect to www.toptal.com port 443: Bad file descriptor
```

**Comment by kondr1** [comment]
can someone answer?
@mingthegit @gobr

**Comment by moltar** [comment]
The other thing I discovered is that now the tool puts very subtle top tap references in the generated files.

That's a very clever way to advertise yourself. 🙃

**Comment by moltar** [comment]
https://github.com/search?q=%22Created+by+https%3A%2F%2Fwww.toptal.com%22&type=code

![image](https://user-images.githubusercontent.com/491247/111554917-d5c3a380-87b9-11eb-9edd-2f82b7556599.png)

**Comment by gobr** [comment]
The app is hosted on toptal.com domain and it generates the resulting files on the fly. All the template files are hosted on https://github.com/toptal/gitignore if you for some reason still want to block the app's address.

**Comment by moltar** [comment]
Great explanation, @gobr, thanks!
