### ISSUE TITLE
Website is in Japanese

### ISSUE THREAD

**Issue by caughtquick** [toptal/gitignore.io#529]
The website is in Japanese , doesn't matter where you login. ![image](https://user-images.githubusercontent.com/62573491/112404768-35481480-8cce-11eb-9bd9-eeaa7db7327d.png)

**Comment by turkoid** [comment]
Getting the same thing.  Tried Firefox, Chrome, Edge and on a different device. Doesn't affect the generation of the files.

**Comment by turkoid** [comment]
Issue has been resolved for me

**Comment by JonAnders** [comment]
For me, it's in Russian. Same bug different language, I guess! 😄

![image](https://user-images.githubusercontent.com/1219682/112618073-0e045b00-8e26-11eb-9141-d8c851a61386.png)

**Comment by gnechita-toptal** [comment]
@caughtquick & @JonAnders can you please tell us if you are still experiencing the issue? We did some changes to Cloudflare recently in order to fix this, and we want to confirm if this worked.

**Comment by JonAnders** [comment]
Yes, it is back to English again now, thanks!

**Comment by caughtquick** [comment]
> @caughtquick & @JonAnders can you please tell us if you are still experiencing the issue? We did some changes to Cloudflare recently in order to fix this, and we want to confirm if this worked.

Still not fixed for me, tried with and without vpn and cleared cache

**Comment by gnechita-toptal** [comment]
> Still not fixed for me, tried with and without vpn and cleared cache

@caughtquick Can you share with me the request your browser is making and also the response you are receving from the website? I'm trying to better understand under which conditions this happens.

[Locales (the `accept-language`  header) influences](https://github.com/toptal/gitignore.io/blob/aedba125d16551aebd46b1cf2437aadaecbe0a61/Sources/App/RouteHandlers/SiteRouteHandlers.swift#L34) our website's appearance.

@JonAnders glad to hear that. Thanks for the reply!

**Comment by dkbay** [comment]
I had this happen to me yesterday but it seems to be fixed now my accept-language header only had this and it's still the same:
![image](https://user-images.githubusercontent.com/1548975/113629808-36325c00-9667-11eb-9e3c-8c48135ede6b.png)

**Comment by gnechita-toptal** [comment]
Thanks for the replies. Glad it got sorted.
