### ISSUE TITLE
The edit box on the website does not work anymore

### ISSUE THREAD

**Issue by Abdelkrim** [toptal/gitignore.io#530]
# Issue Template

## Issue

I can't generate the .gitignore file because I can't add the programming languages inside the edit box.

The edit box bugs!

Here is the screenshot after clicking on the edit box:

![image](https://user-images.githubusercontent.com/791663/112897142-8b0e2980-90df-11eb-8ca3-002dbeec9c6d.png)

### Development Environment:

- [X] Operating System (Name/Version): Ubuntu 20.04
- [X] Web Browser (Name/Version): Chrome or Firefox

### Expected Behavior:

The user inputs the first letters of the programming language and she can select it

### Actual Behavior:

1. We see that the listbox opens but its size is 2-3 pixels only
2. the user can't input anything in the edit box

### Reproduction Steps:

1. open https://www.toptal.com/developers/gitignore
2. click on the edit box

**Comment by lucasgcb** [comment]
Same for me, Ubuntu 20.04 on Firefox; no tags show up and trying to use the API doesn't return anything either.

**Comment by gobr** [comment]
I'm looking into it!

**Comment by gobr** [comment]
I've deployed a fix for this issue.

Thanks @Abdelkrim @lucasgcb for noticing this.
