### ISSUE TITLE
What's the difference between nuxt & nuxtjs?

### ISSUE THREAD

**Issue by djkeh** [toptal/gitignore.io#550]
When you put `nuxt` in gitignore.io website, you get:

https://www.toptal.com/developers/gitignore/api/nuxt

```
# Created by https://www.toptal.com/developers/gitignore/api/nuxt
# Edit at https://www.toptal.com/developers/gitignore?templates=nuxt

### Nuxt ###
# gitignore template for Nuxt.js projects
#
# Recommended template: Node.gitignore

# Nuxt build
.nuxt

# Nuxt generate
dist

# End of https://www.toptal.com/developers/gitignore/api/nuxt
```

If you put `nuxtjs` you get:

https://www.toptal.com/developers/gitignore/api/nuxtjs

```
# Created by https://www.toptal.com/developers/gitignore/api/nuxtjs
# Edit at https://www.toptal.com/developers/gitignore?templates=nuxtjs

### Nuxtjs ###
# dependencies
node_modules

# logs
npm-debug.log

# Nuxt build
.nuxt

# Nuxt generate
dist

# End of https://www.toptal.com/developers/gitignore/api/nuxtjs
```

So what's the difference? I think `nuxt` and `nuxtjs` means the same thing, but two templates exist simultaneously.
The contents are not identical, but are very similar to each other.

If you put two keywords, you get:

https://www.toptal.com/developers/gitignore/api/nuxtjs,nuxt

```
# Created by https://www.toptal.com/developers/gitignore/api/nuxtjs,nuxt
# Edit at https://www.toptal.com/developers/gitignore?templates=nuxtjs,nuxt

### Nuxt ###
# gitignore template for Nuxt.js projects
#
# Recommended template: Node.gitignore

# Nuxt build
.nuxt

# Nuxt generate
dist

### Nuxtjs ###
# dependencies
node_modules

# logs
npm-debug.log

# Nuxt build

# Nuxt generate

# End of https://www.toptal.com/developers/gitignore/api/nuxtjs,nuxt
```

This makes the `.gitignore` script a little bit weird. You'll see there are some comments left on the bottom of `Nuxtjs` section,
because the script already has `.nuxt` and `dist` on the top of `Nuxt` section. I guess the duplicated lines are automatically removed.

The point is, I think we don't need two different templates for `nuxt` and `nuxtjs` as it would make people confused.
Does anyone know the reason gitignore.io had two nuxt templates in different names?
If there's no reason, maybe we can put them together into single nuxtjs template.

### Reference

* https://nuxtjs.org/

**Comment by wick3dr0se** [comment]
They are the same. Nuxt is Nuxt.js. Those are literally just .gitignore files. I'm not sure where you are finding these two different versions on 1 site but the only file hidden in the 'nuxtjs' template you gave is node_modules. Add that to your 'nuxt' template and you will have your own template better than both options. A .gitignore just hides your files when pushing to a repository.. You can hide node_modules, .nuxt, yarn.lock, build/Release, logs, many more if you choose

**Comment by djkeh** [comment]
@wick3dr0se I just couldn't get that you were not sure where I got these templates.
Of course you can find these two separate templates from `gitignore.io` as I do.
That's the reason I'm raising this issue, because it is weird.

https://www.toptal.com/developers/gitignore/api/nuxt,nuxtjs

### To reproduce the issue

1. Go to [gitignore.io](https://www.toptal.com/developers/gitignore)
2. type `nuxt` (see autocomplete works)
3. type `nuxtjs` (see autocomplete works)
4. click the button

**Comment by wick3dr0se** [comment]
That is just an issue within gitignore.io. I highly suggest you learn how to create a .gitignore file from scratch and what can be hidden from your repository. It's not always speciric to the software used. You particular use-case can't be determined with something like gitignore.io sometimes. The .gitignore files are very easy to make and it's easy to look up what can be excluded from a Nuxt.js project. The 2 options you gave are very, very basic .gitignote files. There are many examples of a decent .gitignore for Nuxt across GitHub

**Comment by djkeh** [comment]
@wick3dr0se What? I'm sorry but I don't understand what you're talking about. We are in "THAT" gitignore.io github repository right now, aren't we? You said:

> That is just an issue within gitignore.io

Yes. This is issue space of gitignore.io, you realized this is an issue. So here we are. I'm raising an issue about this. Perhaps you "literally" understood the title of my issue. I'm not saying "What's the difference between nuxt and nuxtjs", that's not my real question. I'm saying:

"What's the difference between nuxt template and nuxtjs template right here?"

I'm not saying I "wonder", I'm saying it's "weird".
That two templates don't have to be separated, as you confirmed that the two words are identical. The content of the template doesn't look nice as well. `nuxtjs` template only has comments except `node_modules`. Both of the structures of comments are looking very close. I presume someone just copied one template to the other, didn't complete it and named it a little bit differently.

Of course I know how to write `.gitignore`, that's out of this issue. Why are you saying that? It seems like you really don't understand this issue from the first place. If the template gitignore.io is showing is wrong, then it's gitignore.io's problem, so we should take care of it. It's not about me writing decent `.gitignore` in my own project. Of course I can do that, and that's totally different matter.

"I found `nuxt` and `nuxtjs` templates, and they do look strange. I suggest we should take care of it, or if there were any reason, I'd like hear it"

This is the real intension of this issue.
Now you get it?

**Comment by wick3dr0se** [comment]
I already mentioned it's a duplicate and they are basically the same thing. I encouraged you to learn some about .gitignore files because you posted it seeming totally lost on what the differences were between the two. This is an issue for gitignore.io but you should have posted something like duplicate template for Nuxt.js if that was your concern. I think you are the one lost as you mentioned the files "look abit weird"

**Comment by wick3dr0se** [comment]
Maybe someone will merge the two but doesn't seem to be much of a relevant _issue_ i'd say

**Comment by djkeh** [comment]
Alright. I don't want misunderstanding. Maybe the text was too vague to explain my point. I updated it.

**Comment by AureliaDontu** [comment]
Hi, sorry but i am beginner so can you help me to fix my problem?
Many thanks
