### ISSUE TITLE
[Question] Is there something like dockerignore.io ?

### ISSUE THREAD

**Issue by kevinadhiguna** [toptal/gitignore.io#562]
## Issue

Hi, I would like to ask if there is something like gitignore.io for .dockerignore.

I am a bit confused as I do not think .gitignore and .dockerignore are same. Let's say I have a Dockerfile. It might be included in .dockerignore but not in .gitignore.

Any suggestion is appreciated !

### Development Environment:

- [x] Machine (Local, Container, Virtual):
- [ ] Operating System (Name/Version):
- [ ] Web Browser (Name/Version):
- [ ] Vapor Version:
- [ ] Swift Version:

**Comment by deniskaber** [comment]
Hello @kevinadhiguna! Yes, you're correct. .gitignore and .dockerignore are not the same.

.dockerignore describes what won't be included into docker context. So, basically, stuff you don't need to build a container, which depends on your project's need.

**Comment by kevinadhiguna** [comment]
I see. Thank you @deniskaber !

**Comment by konstrybakov** [comment]
Official `.dockerignore` docs: https://docs.docker.com/engine/reference/builder/#dockerignore-file

After having a quick search:

- https://github.com/garygitton/dockerignore
- https://github.com/erdaltsksn-old/dockerignore

Not sure there is such a service for `.dockerignore`, but you could also search Github for example usage

Closing this issue! Feel free to reopen if you need any more information
