### ISSUE TITLE
Conflicts between C and D languages

### ISSUE THREAD

**Issue by dokutoku** [toptal/gitignore.io#563]
# Issue Template

## Issue

If you specify both C and D at the same time, the `.d` extension of the D source file will be ignored.

### Expected Behavior:

If both C and D are specified at the same time, as in the following URI, `*.d` will not be specified in .gitignore.

https://www.toptal.com/developers/gitignore/api/c,d

**Comment by dokutoku** [comment]
It seems that `*.d` is defined not only in C, but also in C++ and some other .gitignore.

**Comment by filipechagas** [comment]
Hi @dokutoku 
Thank you for your input!

Both [C.gitignore](https://github.com/github/gitignore/blob/main/C.gitignore) and [D.gitignore](https://github.com/github/gitignore/blob/main/D.gitignore) (as well as [C++.gitignore](https://github.com/github/gitignore/blob/main/C++.gitignore) ) come from https://github.com/github/gitignore and this repository just mirrors them.

Adding this type of logic goes beyond what gitignore.io proposes at this point.
I like your thinking, though. We're preparing a set of UX improvements for the app and your idea will definitely be added to our ideas bucket.
