### ISSUE TITLE
Weird character at the end of the generated ignore with CLI

### ISSUE THREAD

**Issue by Kaijiro** [toptal/gitignore.io#574]
# Issue Template

### Development Environment:

- [x] Machine (Local, Container, Virtual): Local
- [x] Operating System (Name/Version): macOS Big Sur (Version 11.6.2)
- [x] Web Browser (Name/Version): N/A (used the CLI)
- [ ] Vapor Version:
- [ ] Swift Version:

### Expected Behavior:
When calling the CLI, I should get my template in the console.

### Actual Behavior:
I actually have a weird character at the end of my call.

```
...

# Cache file creation bug
# See https://youtrack.jetbrains.com/issue/JBR-2257
.idea/$CACHE_FILE$

# CodeStream plugin
# https://plugins.jetbrains.com/plugin/12206-codestream
.idea/codestream.xml

# End of https://www.toptal.com/developers/gitignore/api/IntelliJ
n%  

```

Notice the "n% " ?

### Reproduction Steps:

- Add the CLI via the tutorial https://docs.gitignore.io/install/command-line
- Generate the ignore part for IntelliJ with `gi IntelliJ`
- Check that there is this weird character at the end of the stream.

**Comment by Kaijiro** [comment]
It appears that the flags used by the curl command makes the weird character appear.

The command auto-generated is 
```bash
function gi() { curl -sLw n https://www.toptal.com/developers/gitignore/api/$@ ;}
```

With zsh, the `-w` flag makes the "n%" appear. I just changed the flag passed : 
```bash

function gi() { curl -sL https://www.toptal.com/developers/gitignore/api/$@ }
```

**Comment by dwmarshall** [comment]
This is a bug in the zsh instructions. I'm looking now for where to update the instructions.

**Comment by dwmarshall** [comment]
Change proposed via joeblau/gitignore.io-docs#4. My fix is to use this command instead:

```
print -r 'function gi() { curl -sLw "\n" https://www.toptal.com/developers/gitignore/api/$@ ;}' >> ~/.zshrc && source ~/.zshrc```
