### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by RajrupDasid** [toptal/gitignore.io#583]
The website not works on Firefox browser Linux

OS-vanilla Arch Linux latest
Firefox version - Latest

Please fix the issue of the website

**Comment by jhult** [comment]
Probably a duplicate of #577 and #576.

**Comment by filipechagas** [comment]
Hi @RajrupDasid 
Thanks for the report.

This is probably related to https://github.com/toptal/gitignore.io/issues/577 and https://github.com/toptal/gitignore.io/issues/576
A fix has been released.

If you still encounter any problems, please let us know.

**Comment by RajrupDasid** [comment]
@filipechagas Hi sir , Actually I am still facing the issue mentioned above from both normal Firefox and Firefox Developer Edition.

button is acting like false or not taking POST request , from the mentioned browsers .
I am on the latest versions on them

**Comment by filipechagas** [comment]
@RajrupDasid Thank you for the feedback! We're looking into that.
I've reopened https://github.com/toptal/gitignore.io/issues/577 and will be posting updates there.

**Comment by RajrupDasid** [comment]
yes thanks it's now working as before making my work smooth thanks team
