### ISSUE TITLE
Add `.gitignore` as suffix to URL (feature request)

### ISSUE THREAD

**Issue by asinghani** [toptal/gitignore.io#587]
It would be handy if instead of the URL ending with the list of templates, it ended with `.gitignore` so that it could be fed directly into `wget`, save-as, etc. and get a file named `.gitignore`

i.e. instead of `https://www.toptal.com/developers/gitignore/api/python,linux,vim`, having it be `https://www.toptal.com/developers/gitignore/api/python,linux,vim/.gitignore` so the "filename" becomes `.gitignore`

**Comment by konstrybakov** [comment]
Hey @asinghani! Thank you for taking the time to suggest this.

Did you know you could [install a `gi` function](https://docs.gitignore.io/install/command-line) for your cli of choice and then use it like [this](https://docs.gitignore.io/use/command-line#project).

```
gi java,python >> .gitignore
```

Would it not be enough for your usecase?
