### ISSUE TITLE
macOS zsh installation instructions wrong

### ISSUE THREAD

**Issue by lukens** [toptal/gitignore.io#608]
The current command line installation instructions for zsh don't work, and cause all output to have an `n` placed after it.

Current command given in the instructions is:

```
echo "function gi() { curl -sLw "\n" https://www.toptal.com/developers/gitignore/api/\$@ ;}" >> \
~/.zshrc && source ~/.zshrc
```

However, this needs extra escaping, as the `"\n"` is ending up as just `n`.

I found the following worked:

```
echo "function gi() { curl -sLw \"\\\n\" https://www.toptal.com/developers/gitignore/api/\$@ ;}" >> \
~/.zshrc && source ~/.zshrc
```

I've tested on macOs and Linux, and the same applies to both.

**Versions used:**
*macOs:*
`zsh 5.8.1 (x86_64-apple-darwin22.0)`
`macOS 13.2 (22D49)`

*Linux:*
`zsh 5.8.1 (aarch64-unknown-linux-gnu)`
`Ubuntu 22.04.1 LTS`

**Comment by filipechagas** [comment]
Hi @lukens ! Thank you for pointing it out.

We'd happily accept a PR with the fix if you're willing to do that.
Otherwise, we'll be adding this to our backlog.

**Comment by filipechagas** [comment]
@lukens true! This documentation page is powered by Gitbooks. I have added this issue to our backlog and will work on the fix soon (tm).

**Comment by filipechagas** [comment]
The docs are currently stored in https://github.com/joeblau/gitignore.io-docs

**Comment by filipechagas** [comment]
Thank you again for the report, @lukens !
Your changes have been published

**Comment by lukens** [comment]
It looks like only the macOS instructions have been updated, but this also applies to zsh for Linux, as far as I can tell.

This is really my fault, as it only said "macOS" in the subject. I'd started typing the issue out before thinking to test in Linux too, and it seems I then forgot to go back and change the subject (which I have now done).

**Comment by filipechagas** [comment]
@lukens Truuuue! That's totally my fault. 
I just published the change for linux instructions as well. It should pop in in a couple of minutes after cache revalidation.

Thank you again for pointing it out!!!
