### ISSUE TITLE
Feature Request: CLI tool that talks with GitHub directly

### ISSUE THREAD

**Issue by martin-braun** [toptal/gitignore.io#613]
Today I experience slowness of the website. GitHub loads fine, so I assume the server is under load for some reason? That got me thinking, it would be nice to have a `gi` tool that talks directly with GitHub to generate my `.gitignore` so there is no dependency on `gitignore.io`.

**Comment by mcarneiro** [comment]
Hi @martin-braun, we haven't checked anything out of the ordinary in the error rate or response time in our servers:

![image](https://user-images.githubusercontent.com/349282/225478062-68603077-643e-4cd7-903c-6dffb024d123.png)
Even in our spikes, the requests keep under 300ms (average of 10 minutes). Do you think that could be generated by a local issue?

Using raw files directly from Github could be an alternative for a fork, but I feel it contradicts the current architecture.
